##
## Unit Tests
##
name: test
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  unit:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - uses: actions/checkout@v4.1.1
     
      - name: go build
        run: |
          go build ./...
    
      - name: go test
        run: |
          go test -v -coverprofile=profile.cov $(go list ./... | grep -v /examples/)

      - uses: shogo82148/actions-goveralls@v1
        continue-on-error: true
        with:
          path-to-profile: profile.cov
